---
- name: Creating AD groups and users
  hosts: CHANGE_ME
  vars:
    domainname: EXAMPLE.COM
    dnsname: example.com
    domain_admin: Administrator@example.com
    user_password: CHANGE_ME

  tasks:

    - name: CHANGE_ME {{ domainname }}
      ANSIBLE_MODULE:
        name: CHANGE_ME
        scope: CHANGE_ME
        category: CHANGE_ME
        attributes:
          mail: CHANGE_ME
          wWWHomePage: CHANGE_ME
        ignore_protection: yes

    - name: CHANGE_ME
      ANSIBLE_MODULE:
        name: CHANGE_ME
        firstname: CHANGE_ME
        lastname: CHANGE_ME
        password: CHANGE_ME
        state: CHANGE_ME
        groups:
          - Domain Users
          - CHANGE_ME
        street: 125 42nd St.
        city: Sometown
        state_province: CA
        postal_code: 1234
        country: US
        attributes:
          telephoneNumber: 543-123456